version: "2"
services:
  web:
    container_name: engetecnica_web
    privileged: true
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
    - "8000:80"
    - "9000:443"
    expose: 
      - '80'
      - '443'
    volumes:
    - ./:/var/www/html/
    - ./log:/var/log/apache2
    links:
      - db

  db:
    container_name: engetecnica_db
    image: mariadb
    ports:
      - "33061:3306"
    expose: 
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=engetecnica
    volumes:
      - ./setup/my.cnf:/etc/my.cnf
      - engetecnica:/var/lib/mysql
    restart: always

volumes:
  engetecnica:
    external: true